/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/activity-card.vue')['default']
    Anchor: typeof import('./src/components/anchor.vue')['default']
    ConfigProvider: typeof import('./src/components/config-provider.vue')['default']
    ConfirmModal: typeof import('./src/components/confirm-modal.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    Elevator: typeof import('./src/components/elevator.vue')['default']
    FieldCell: typeof import('./src/components/field-cell.vue')['default']
    FilterMenu: typeof import('./src/components/filter-menu.vue')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    MyScrollView: typeof import('./src/components/my-scroll-view.vue')['default']
    NotificationButton: typeof import('./src/components/notification-button.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    SignUpPopup: typeof import('./src/components/sign-up-popup.vue')['default']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    TabPage: typeof import('./src/components/tab-page.vue')['default']
  }
}
